remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
title: My A-Frame Project
baseurl: "/charity-everett"
url: "https://charityeverett.github.io"
exclude:
  - node_modules
  - package.json
  - package-lock.json
  - README.md
  - Gemfile
  - Gemfile.lock
  - .gitignore
]