remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap

title: Charity Everett's VR Tech Writing Portfolio
url: "https://charityeverett.github.io"
description: "A virtual A-Frame portfolio showcasing tech writing projects"

exclude:
  - node_modules
  - package.json
  - package-lock.json
  - README.md
  - Gemfile
  - Gemfile.lock
  - .gitignore
